#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: cpp-init-default <project-name>"
    echo "Initializes a brand new C++ project in a new directory"
    exit 1;
fi

PROJECT_NAME="$1"

echo "*** Creating C++ project ..."
mkdir "$PROJECT_NAME"
cd "$PROJECT_NAME"

echo
echo "*** Creating empty git repo ..."
git init
git commit --allow-empty -m "New repo"

echo
echo "*** Creating .gitignore ..."
cat > .gitignore << 'EOF'
# Visual Studio artifacts
out/
.vs/
CMakeSettings.json
EOF

git add .gitignore
git commit -m "Added .gitignore"

echo
echo "*** Creating MIT license ..."
cat > LICENSE << EOF
MIT License

Copyright (c) $(date +%Y) 

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF

git add LICENSE
git commit -m "Added MIT License"

echo
echo "*** Creating default README.md ..."
echo "# $PROJECT_NAME" > README.md
git add README.md
git commit -m "Added default README.md"

echo
echo "*** Creating default CMakeLists.txt ..."
sed "s/@PROJECT_NAME@/$PROJECT_NAME/g" ../\!EXE_TEMPLATE_CMakeLists.txt.in > CMakeLists.txt
git add CMakeLists.txt
git commit -m "Added default CMakeLists.txt"

echo
echo "*** Creating a placeholder main.cpp, but not committing it ..."
cat > main.cpp << 'EOF'
#include <iostream>

int main(char * argv[], int argc)
{
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
EOF

echo
echo "*** C++ project '$PROJECT_NAME' created"

