#!/usr/bin/env bash
#
# Fetches updates from remotes and fast-forwards or creates all remote branches.

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: git-ffwd [remote ...]"
    echo "Fetches and fast-forwards (if possible) all remote branches in the repo."
    echo "If no remotes are specified, all remotes are processed."
    exit 0
fi

# Determine the remotes to process
REMOTES="$@"
if [ -z "$REMOTES" ]; then
  REMOTES=$(git remote)
fi
REMOTES=$(echo "$REMOTES" | xargs -n1 echo)

# Exit if no remotes are found
if [ -z "$REMOTES" ]; then
  echo "No remotes found in this repository."
  exit 0
fi

CLB=$(git symbolic-ref --short HEAD) # current local branch

# Process each remote
echo "$REMOTES" | while read REMOTE; do
  git remote update "$REMOTE"
  if [ $? -ne 0 ]; then
    echo "Failed to update remote $REMOTE" >&2
    continue
  fi

  # Process each remote-local branch pair for the current remote
  BRANCH_INFO=$(git remote show "$REMOTE" -n | awk '/merges with remote/{print $5" "$1}')
  echo "$BRANCH_INFO" | while read line; do
    RB=$(echo "$line"|cut -f1 -d" ") # remote branch
    ARB="refs/remotes/$REMOTE/$RB" # absolute remote branch
    LB=$(echo "$line"|cut -f2 -d" ") # local branch
    ALB="refs/heads/$LB" # absolute local branch

    # If the local branch is ahead, then do nothing other than note if there is a divergence
    # Otherwise, if the local branch is behind, then fast-forward it
    NAHEAD=$(( $(git rev-list --count "$ARB".."$ALB" 2>/dev/null) +0 ))
    NBEHIND=$(( $(git rev-list --count "$ALB".."$ARB" 2>/dev/null) +0 ))
    if [ $NAHEAD -gt 0 ]; then
      if [ $NBEHIND -gt 0 ]; then
        echo " branch $LB is $NBEHIND commit(s) behind and $NAHEAD commit(s) ahead of $REMOTE/$RB. could not be fast-forwarded"
      fi
    elif [ $NBEHIND -gt 0 ]; then
      if [ "$LB" = "$CLB" ]; then
        echo " branch $LB was $NBEHIND commit(s) behind of $REMOTE/$RB. fast-forward merge"
        git merge -q "$ARB"
      else
        echo " branch $LB was $NBEHIND commit(s) behind of $REMOTE/$RB. resetting local branch to remote"
        git branch -f "$LB" "$ARB" >/dev/null
      fi
    fi
  done
done
