#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: git-pull-branch <branch>"
    echo "Pulls <branch> and rebases the current branch on top of it"
    exit 1;
fi

current_branch=$(git symbolic-ref -q HEAD)
current_branch=${current_branch##refs/heads/}

git checkout $1 && git pull && git rebase $1 $current_branch
