#!/bin/bash

## For each repo in all subdirectories, this pulls all branches from all remotes

# Find git repos and loop over them:
for repo in `find . -type d -name ".git"`
do
    # cd to the dir that contains .git/:
    dir=`echo ${repo} | sed -e 's/\/.git/\//'`
    cd ${dir}
    echo ${dir}

    # Fetch all branches from all remotes
    git fetch --all --tags --prune

    # Pull all tracking branches from all remotes
    git pull --all

    # cd back
    echo
    cd - &> /dev/null
done
