#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: git-stash-commits <commit> [<branch>]"
    echo "Resets the current branch to the specified commit and moves the removed commits to a new branch."
    echo "The new branch name defaults to the current branch name with '-wip' appended."
    exit 1;
fi

commit=$1
if [ $# -ge 2 ]; then
    branch=$2
else
    branch=`git rev-parse --abbrev-ref HEAD`-wip
fi

echo "Creating branch $branch" && git branch $branch && git reset --hard $commit
