#!/usr/bin/env bash
# version: 1.0.0
#
# Shows the differences between a commit and its predecessor using difftool

set -e  # Exit on error

if [ $# -ne 1 ]; then
    echo "Usage: git-showtool <commit>"
    echo "Shows the differences between a commit and its predecessor using difftool"
    exit 1;
fi

git difftool --dir-diff "$1~1..$1"
