#!/usr/bin/env bash
#
# Runs git difftool in parallel on all files that differ between the working directory and HEAD

if [ $# -gt 1 ]; then
    echo "Usage: git-difftool-all [path]"
    echo "Displays the differences for <path> between the working directory and HEAD using difftool"
    exit 1;
fi

files=$(git diff --name-only "$1")
if [ -z "$files" ]; then
    echo "No differences found."
    exit 0
fi
while IFS= read -r name; do
    git difftool -y "$name" &
done <<< "$files"

wait
