#!/bin/bash

if [ $# -ne 0 ]; then
    echo "Usage: git-ffwd-all"
    echo "Fetches and fast-forwards (if possible) all branches in the repo and all its submodules"
    exit 1;
fi

git-ffwd
git submodule foreach git-ffwd
