#!/bin/bash

if [ $# -ne 0 ]; then
    echo "Usage: yarn-init-default"
    echo "Initializes a brand new node project using yarn"
    exit 1;
fi

echo "*** Creating git repo ..."
git init
git commit --allow-empty -m "New repo"

echo
echo "*** Creating .gitignore ..."
npx gitignore node
git add --all
git commit -m "Added default .gitignore"

echo
echo "*** Creating MIT license ..."
npx license MIT
git add --all
git commit -m "Added MIT License"

echo
echo "*** Initializing node project using yarn 2... ***"
yarn init -2 -p
echo "" >> .yarnrc.yml
echo "# Some node projects require node_modules" >> .yarnrc.yml
echo "#nodeLinker: node-modules" >> .yarnrc.yml
yarn install
git add --all
git commit -m "Added yarn, default README.md, and default package.json"
